// Package mksclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package mksclient

import (
	"time"
)

// Defines values for ClusterCniType.
const (
	ClusterCniTypeCALICO ClusterCniType = "CALICO"
	ClusterCniTypeCILIUM ClusterCniType = "CILIUM"
)

// Valid indicates whether the value is a known member of the ClusterCniType enum.
func (e ClusterCniType) Valid() bool {
	switch e {
	case ClusterCniTypeCALICO:
		return true
	case ClusterCniTypeCILIUM:
		return true
	default:
		return false
	}
}

// Defines values for ClusterNetworkType.
const (
	ClusterNetworkTypeL3VPN    ClusterNetworkType = "L3VPN"
	ClusterNetworkTypeSTANDARD ClusterNetworkType = "STANDARD"
)

// Valid indicates whether the value is a known member of the ClusterNetworkType enum.
func (e ClusterNetworkType) Valid() bool {
	switch e {
	case ClusterNetworkTypeL3VPN:
		return true
	case ClusterNetworkTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for ClusterStatus.
const (
	ClusterStatusACTIVE   ClusterStatus = "ACTIVE"
	ClusterStatusCREATING ClusterStatus = "CREATING"
	ClusterStatusDELETED  ClusterStatus = "DELETED"
	ClusterStatusERROR    ClusterStatus = "ERROR"
)

// Valid indicates whether the value is a known member of the ClusterStatus enum.
func (e ClusterStatus) Valid() bool {
	switch e {
	case ClusterStatusACTIVE:
		return true
	case ClusterStatusCREATING:
		return true
	case ClusterStatusDELETED:
		return true
	case ClusterStatusERROR:
		return true
	default:
		return false
	}
}

// Defines values for ClusterDetailedCniType.
const (
	ClusterDetailedCniTypeCALICO ClusterDetailedCniType = "CALICO"
	ClusterDetailedCniTypeCILIUM ClusterDetailedCniType = "CILIUM"
)

// Valid indicates whether the value is a known member of the ClusterDetailedCniType enum.
func (e ClusterDetailedCniType) Valid() bool {
	switch e {
	case ClusterDetailedCniTypeCALICO:
		return true
	case ClusterDetailedCniTypeCILIUM:
		return true
	default:
		return false
	}
}

// Defines values for ClusterDetailedNetworkType.
const (
	ClusterDetailedNetworkTypeL3VPN    ClusterDetailedNetworkType = "L3VPN"
	ClusterDetailedNetworkTypeSTANDARD ClusterDetailedNetworkType = "STANDARD"
)

// Valid indicates whether the value is a known member of the ClusterDetailedNetworkType enum.
func (e ClusterDetailedNetworkType) Valid() bool {
	switch e {
	case ClusterDetailedNetworkTypeL3VPN:
		return true
	case ClusterDetailedNetworkTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for ClusterDetailedStatus.
const (
	ClusterDetailedStatusACTIVE                             ClusterDetailedStatus = "ACTIVE"
	ClusterDetailedStatusERROR                              ClusterDetailedStatus = "ERROR"
	ClusterDetailedStatusMAINTENANCE                        ClusterDetailedStatus = "MAINTENANCE"
	ClusterDetailedStatusPENDINGCREATE                      ClusterDetailedStatus = "PENDING_CREATE"
	ClusterDetailedStatusPENDINGDELETE                      ClusterDetailedStatus = "PENDING_DELETE"
	ClusterDetailedStatusPENDINGNODEREINSTALL               ClusterDetailedStatus = "PENDING_NODE_REINSTALL"
	ClusterDetailedStatusPENDINGNODESUNSHELVE               ClusterDetailedStatus = "PENDING_NODES_UNSHELVE"
	ClusterDetailedStatusPENDINGREINSTALLMASTERS            ClusterDetailedStatus = "PENDING_REINSTALL_MASTERS"
	ClusterDetailedStatusPENDINGRESIZE                      ClusterDetailedStatus = "PENDING_RESIZE"
	ClusterDetailedStatusPENDINGROTATECERTS                 ClusterDetailedStatus = "PENDING_ROTATE_CERTS"
	ClusterDetailedStatusPENDINGUPDATE                      ClusterDetailedStatus = "PENDING_UPDATE"
	ClusterDetailedStatusPENDINGUPDATENODEGROUP             ClusterDetailedStatus = "PENDING_UPDATE_NODEGROUP"
	ClusterDetailedStatusPENDINGUPDATEREGISTRIESINTEGRATION ClusterDetailedStatus = "PENDING_UPDATE_REGISTRIES_INTEGRATION"
	ClusterDetailedStatusPENDINGUPGRADE                     ClusterDetailedStatus = "PENDING_UPGRADE"
	ClusterDetailedStatusPENDINGUPGRADECLUSTERCONFIGURATION ClusterDetailedStatus = "PENDING_UPGRADE_CLUSTER_CONFIGURATION"
	ClusterDetailedStatusPENDINGUPGRADEMASTERSCONFIGURATION ClusterDetailedStatus = "PENDING_UPGRADE_MASTERS_CONFIGURATION"
	ClusterDetailedStatusPENDINGUPGRADEMINORVERSION         ClusterDetailedStatus = "PENDING_UPGRADE_MINOR_VERSION"
	ClusterDetailedStatusPENDINGUPGRADEPATCHVERSION         ClusterDetailedStatus = "PENDING_UPGRADE_PATCH_VERSION"
)

// Valid indicates whether the value is a known member of the ClusterDetailedStatus enum.
func (e ClusterDetailedStatus) Valid() bool {
	switch e {
	case ClusterDetailedStatusACTIVE:
		return true
	case ClusterDetailedStatusERROR:
		return true
	case ClusterDetailedStatusMAINTENANCE:
		return true
	case ClusterDetailedStatusPENDINGCREATE:
		return true
	case ClusterDetailedStatusPENDINGDELETE:
		return true
	case ClusterDetailedStatusPENDINGNODEREINSTALL:
		return true
	case ClusterDetailedStatusPENDINGNODESUNSHELVE:
		return true
	case ClusterDetailedStatusPENDINGREINSTALLMASTERS:
		return true
	case ClusterDetailedStatusPENDINGRESIZE:
		return true
	case ClusterDetailedStatusPENDINGROTATECERTS:
		return true
	case ClusterDetailedStatusPENDINGUPDATE:
		return true
	case ClusterDetailedStatusPENDINGUPDATENODEGROUP:
		return true
	case ClusterDetailedStatusPENDINGUPDATEREGISTRIESINTEGRATION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADE:
		return true
	case ClusterDetailedStatusPENDINGUPGRADECLUSTERCONFIGURATION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADEMASTERSCONFIGURATION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADEMINORVERSION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADEPATCHVERSION:
		return true
	default:
		return false
	}
}

// Defines values for DedicatedNodegroupConfigCurrency.
const (
	Bonus DedicatedNodegroupConfigCurrency = "bonus"
	Main  DedicatedNodegroupConfigCurrency = "main"
)

// Valid indicates whether the value is a known member of the DedicatedNodegroupConfigCurrency enum.
func (e DedicatedNodegroupConfigCurrency) Valid() bool {
	switch e {
	case Bonus:
		return true
	case Main:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupNodegroupType.
const (
	NodegroupNodegroupTypeDEDICATED    NodegroupNodegroupType = "DEDICATED"
	NodegroupNodegroupTypeDEDICATEDGPU NodegroupNodegroupType = "DEDICATED_GPU"
	NodegroupNodegroupTypeGPU          NodegroupNodegroupType = "GPU"
	NodegroupNodegroupTypeSTANDARD     NodegroupNodegroupType = "STANDARD"
)

// Valid indicates whether the value is a known member of the NodegroupNodegroupType enum.
func (e NodegroupNodegroupType) Valid() bool {
	switch e {
	case NodegroupNodegroupTypeDEDICATED:
		return true
	case NodegroupNodegroupTypeDEDICATEDGPU:
		return true
	case NodegroupNodegroupTypeGPU:
		return true
	case NodegroupNodegroupTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupStatus.
const (
	NodegroupStatusACTIVE               NodegroupStatus = "ACTIVE"
	NodegroupStatusERROR                NodegroupStatus = "ERROR"
	NodegroupStatusPENDINGCREATE        NodegroupStatus = "PENDING_CREATE"
	NodegroupStatusPENDINGDELETE        NodegroupStatus = "PENDING_DELETE"
	NodegroupStatusPENDINGNODEREINSTALL NodegroupStatus = "PENDING_NODE_REINSTALL"
	NodegroupStatusPENDINGNODESUNSHELVE NodegroupStatus = "PENDING_NODES_UNSHELVE"
	NodegroupStatusPENDINGSCALEDOWN     NodegroupStatus = "PENDING_SCALE_DOWN"
	NodegroupStatusPENDINGSCALEUP       NodegroupStatus = "PENDING_SCALE_UP"
	NodegroupStatusPENDINGUPDATE        NodegroupStatus = "PENDING_UPDATE"
)

// Valid indicates whether the value is a known member of the NodegroupStatus enum.
func (e NodegroupStatus) Valid() bool {
	switch e {
	case NodegroupStatusACTIVE:
		return true
	case NodegroupStatusERROR:
		return true
	case NodegroupStatusPENDINGCREATE:
		return true
	case NodegroupStatusPENDINGDELETE:
		return true
	case NodegroupStatusPENDINGNODEREINSTALL:
		return true
	case NodegroupStatusPENDINGNODESUNSHELVE:
		return true
	case NodegroupStatusPENDINGSCALEDOWN:
		return true
	case NodegroupStatusPENDINGSCALEUP:
		return true
	case NodegroupStatusPENDINGUPDATE:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupDetailedNodegroupType.
const (
	NodegroupDetailedNodegroupTypeDEDICATED    NodegroupDetailedNodegroupType = "DEDICATED"
	NodegroupDetailedNodegroupTypeDEDICATEDGPU NodegroupDetailedNodegroupType = "DEDICATED_GPU"
	NodegroupDetailedNodegroupTypeGPU          NodegroupDetailedNodegroupType = "GPU"
	NodegroupDetailedNodegroupTypeSTANDARD     NodegroupDetailedNodegroupType = "STANDARD"
)

// Valid indicates whether the value is a known member of the NodegroupDetailedNodegroupType enum.
func (e NodegroupDetailedNodegroupType) Valid() bool {
	switch e {
	case NodegroupDetailedNodegroupTypeDEDICATED:
		return true
	case NodegroupDetailedNodegroupTypeDEDICATEDGPU:
		return true
	case NodegroupDetailedNodegroupTypeGPU:
		return true
	case NodegroupDetailedNodegroupTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupDetailedStatus.
const (
	NodegroupDetailedStatusACTIVE               NodegroupDetailedStatus = "ACTIVE"
	NodegroupDetailedStatusERROR                NodegroupDetailedStatus = "ERROR"
	NodegroupDetailedStatusPENDINGCREATE        NodegroupDetailedStatus = "PENDING_CREATE"
	NodegroupDetailedStatusPENDINGDELETE        NodegroupDetailedStatus = "PENDING_DELETE"
	NodegroupDetailedStatusPENDINGNODEREINSTALL NodegroupDetailedStatus = "PENDING_NODE_REINSTALL"
	NodegroupDetailedStatusPENDINGNODESUNSHELVE NodegroupDetailedStatus = "PENDING_NODES_UNSHELVE"
	NodegroupDetailedStatusPENDINGSCALEDOWN     NodegroupDetailedStatus = "PENDING_SCALE_DOWN"
	NodegroupDetailedStatusPENDINGSCALEUP       NodegroupDetailedStatus = "PENDING_SCALE_UP"
	NodegroupDetailedStatusPENDINGUPDATE        NodegroupDetailedStatus = "PENDING_UPDATE"
)

// Valid indicates whether the value is a known member of the NodegroupDetailedStatus enum.
func (e NodegroupDetailedStatus) Valid() bool {
	switch e {
	case NodegroupDetailedStatusACTIVE:
		return true
	case NodegroupDetailedStatusERROR:
		return true
	case NodegroupDetailedStatusPENDINGCREATE:
		return true
	case NodegroupDetailedStatusPENDINGDELETE:
		return true
	case NodegroupDetailedStatusPENDINGNODEREINSTALL:
		return true
	case NodegroupDetailedStatusPENDINGNODESUNSHELVE:
		return true
	case NodegroupDetailedStatusPENDINGSCALEDOWN:
		return true
	case NodegroupDetailedStatusPENDINGSCALEUP:
		return true
	case NodegroupDetailedStatusPENDINGUPDATE:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupListItemNodegroupType.
const (
	DEDICATED    NodegroupListItemNodegroupType = "DEDICATED"
	DEDICATEDGPU NodegroupListItemNodegroupType = "DEDICATED_GPU"
	GPU          NodegroupListItemNodegroupType = "GPU"
	STANDARD     NodegroupListItemNodegroupType = "STANDARD"
)

// Valid indicates whether the value is a known member of the NodegroupListItemNodegroupType enum.
func (e NodegroupListItemNodegroupType) Valid() bool {
	switch e {
	case DEDICATED:
		return true
	case DEDICATEDGPU:
		return true
	case GPU:
		return true
	case STANDARD:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupListItemStatus.
const (
	NodegroupListItemStatusACTIVE               NodegroupListItemStatus = "ACTIVE"
	NodegroupListItemStatusERROR                NodegroupListItemStatus = "ERROR"
	NodegroupListItemStatusPENDINGCREATE        NodegroupListItemStatus = "PENDING_CREATE"
	NodegroupListItemStatusPENDINGDELETE        NodegroupListItemStatus = "PENDING_DELETE"
	NodegroupListItemStatusPENDINGNODEREINSTALL NodegroupListItemStatus = "PENDING_NODE_REINSTALL"
	NodegroupListItemStatusPENDINGNODESUNSHELVE NodegroupListItemStatus = "PENDING_NODES_UNSHELVE"
	NodegroupListItemStatusPENDINGSCALEDOWN     NodegroupListItemStatus = "PENDING_SCALE_DOWN"
	NodegroupListItemStatusPENDINGSCALEUP       NodegroupListItemStatus = "PENDING_SCALE_UP"
	NodegroupListItemStatusPENDINGUPDATE        NodegroupListItemStatus = "PENDING_UPDATE"
)

// Valid indicates whether the value is a known member of the NodegroupListItemStatus enum.
func (e NodegroupListItemStatus) Valid() bool {
	switch e {
	case NodegroupListItemStatusACTIVE:
		return true
	case NodegroupListItemStatusERROR:
		return true
	case NodegroupListItemStatusPENDINGCREATE:
		return true
	case NodegroupListItemStatusPENDINGDELETE:
		return true
	case NodegroupListItemStatusPENDINGNODEREINSTALL:
		return true
	case NodegroupListItemStatusPENDINGNODESUNSHELVE:
		return true
	case NodegroupListItemStatusPENDINGSCALEDOWN:
		return true
	case NodegroupListItemStatusPENDINGSCALEUP:
		return true
	case NodegroupListItemStatusPENDINGUPDATE:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupTaintEffect.
const (
	NoExecute        NodegroupTaintEffect = "NoExecute"
	NoSchedule       NodegroupTaintEffect = "NoSchedule"
	PreferNoSchedule NodegroupTaintEffect = "PreferNoSchedule"
)

// Valid indicates whether the value is a known member of the NodegroupTaintEffect enum.
func (e NodegroupTaintEffect) Valid() bool {
	switch e {
	case NoExecute:
		return true
	case NoSchedule:
		return true
	case PreferNoSchedule:
		return true
	default:
		return false
	}
}

// Defines values for RegistriesIntegrationStatus.
const (
	RegistriesIntegrationStatusACTIVE        RegistriesIntegrationStatus = "ACTIVE"
	RegistriesIntegrationStatusDELETED       RegistriesIntegrationStatus = "DELETED"
	RegistriesIntegrationStatusERROR         RegistriesIntegrationStatus = "ERROR"
	RegistriesIntegrationStatusINACTIVE      RegistriesIntegrationStatus = "INACTIVE"
	RegistriesIntegrationStatusPENDINGCREATE RegistriesIntegrationStatus = "PENDING_CREATE"
	RegistriesIntegrationStatusPENDINGDELETE RegistriesIntegrationStatus = "PENDING_DELETE"
	RegistriesIntegrationStatusPENDINGUPDATE RegistriesIntegrationStatus = "PENDING_UPDATE"
	RegistriesIntegrationStatusUNKNOWN       RegistriesIntegrationStatus = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the RegistriesIntegrationStatus enum.
func (e RegistriesIntegrationStatus) Valid() bool {
	switch e {
	case RegistriesIntegrationStatusACTIVE:
		return true
	case RegistriesIntegrationStatusDELETED:
		return true
	case RegistriesIntegrationStatusERROR:
		return true
	case RegistriesIntegrationStatusINACTIVE:
		return true
	case RegistriesIntegrationStatusPENDINGCREATE:
		return true
	case RegistriesIntegrationStatusPENDINGDELETE:
		return true
	case RegistriesIntegrationStatusPENDINGUPDATE:
		return true
	case RegistriesIntegrationStatusUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	CANCELED   TaskStatus = "CANCELED"
	DONE       TaskStatus = "DONE"
	ERROR      TaskStatus = "ERROR"
	INPROGRESS TaskStatus = "IN_PROGRESS"
	INQUEUE    TaskStatus = "IN_QUEUE"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case CANCELED:
		return true
	case DONE:
		return true
	case ERROR:
		return true
	case INPROGRESS:
		return true
	case INQUEUE:
		return true
	default:
		return false
	}
}

// Defines values for Lang.
const (
	LangEn Lang = "en"
	LangRu Lang = "ru"
)

// Valid indicates whether the value is a known member of the Lang enum.
func (e Lang) Valid() bool {
	switch e {
	case LangEn:
		return true
	case LangRu:
		return true
	default:
		return false
	}
}

// Defines values for GetClusterActionsV2ParamsLang.
const (
	GetClusterActionsV2ParamsLangEn GetClusterActionsV2ParamsLang = "en"
	GetClusterActionsV2ParamsLangRu GetClusterActionsV2ParamsLang = "ru"
)

// Valid indicates whether the value is a known member of the GetClusterActionsV2ParamsLang enum.
func (e GetClusterActionsV2ParamsLang) Valid() bool {
	switch e {
	case GetClusterActionsV2ParamsLangEn:
		return true
	case GetClusterActionsV2ParamsLangRu:
		return true
	default:
		return false
	}
}

// Defines values for GetNodegroupActionsV2ParamsLang.
const (
	En GetNodegroupActionsV2ParamsLang = "en"
	Ru GetNodegroupActionsV2ParamsLang = "ru"
)

// Valid indicates whether the value is a known member of the GetNodegroupActionsV2ParamsLang enum.
func (e GetNodegroupActionsV2ParamsLang) Valid() bool {
	switch e {
	case En:
		return true
	case Ru:
		return true
	default:
		return false
	}
}

// Action defines model for Action.
type Action struct {
	// Available Available set true when action is available for current object.
	Available bool `json:"available"`

	// Reason Reason explains why available is false, skipped when available is true.
	Reason string `json:"reason,omitempty"`
}

// AdmissionControllersList List of available admission controllers.
type AdmissionControllersList struct {
	AdmissionControllers *[]AvailableAdmissionControllers `json:"admission_controllers,omitempty"`
}

// AuditLogs defines model for AuditLogs.
type AuditLogs struct {
	// Enabled If `enabled` kubernetes audit logs should be collected
	// and pushed into SIEM system (e.g. logstash).
	// False by default.
	Enabled bool `json:"enabled"`

	// SecretName Contains name of the kubernetes secret in namespace kube-system with credentials of SIEM system where logs should be pushed. Fields of the secret: host, port, username (optional), password (optional), ca.crt (optional). This field is optional. By default, used mks-audit-logs. Secret name should be as a DNS subdomain name as defined in RFC 1123. [More Information.](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names)
	SecretName string `json:"secret_name"`
}

// AvailableAdmissionControllers AvailableAdmissionControllers represents detailed info about available admission controllers
// for every k8s minor version.
type AvailableAdmissionControllers struct {
	// KubeVersionMinor Kubernetes minor version.
	KubeVersionMinor *string `json:"kube_version_minor,omitempty"`

	// Names List of available admission controllers.
	Names *OptionNamesAC `json:"names,omitempty"`
}

// AvailableFeatureGates AvailableFeatureGates represents detailed info about available feature gates
// for every k8s minor version.
type AvailableFeatureGates struct {
	// KubeVersionMinor Kubernetes minor version.
	KubeVersionMinor *string `json:"kube_version_minor,omitempty"`

	// Names List of available feature gate names.
	Names *OptionNamesFG `json:"names,omitempty"`
}

// CNICiliumSettings Represents settings for Cilium CNI if this CNI was chosen as "cni_type".
// Otherwise settings will be ignored.
type CNICiliumSettings struct {
	// EnvoyDaemonset Enables Envoy DaemonSet for Cilium CNI.
	EnvoyDaemonset *bool `json:"envoy_daemonset,omitempty"`

	// HubbleRelay Enables hubble relay for Cilium CNI.
	HubbleRelay *bool `json:"hubble_relay,omitempty"`
}

// CloudNodegroupConfig Represents configuration for cloud based nodegroups.
type CloudNodegroupConfig struct {
	// AffinityPolicy An optional parameter to tune nodes affinity.
	AffinityPolicy string `json:"affinity_policy,omitempty"`

	// Cpus Represents CPU count for each node.
	// It can be omitted only in cases when flavor_id is set.
	Cpus int64 `json:"cpus,omitempty"`

	// FlavorId Contains reference to a pre-created flavor. It can be omitted in most cases.
	FlavorId string `json:"flavor_id,omitempty"`

	// KeypairName Contains name of the SSH key that will be added to all nodes.
	KeypairName string `json:"keypair_name,omitempty"`

	// LocalVolume Represents if nodes will use local volume.
	LocalVolume bool `json:"local_volume,omitempty"`

	// RamMb Represents RAM count in MB for each node.
	// It can be omitted only in cases when flavor_id is set.
	RamMb int64 `json:"ram_mb,omitempty"`

	// VolumeGb Represents volume size in GB for each node.
	// It can be omitted only in cases when flavor_id is set and volume is local.
	VolumeGb int64 `json:"volume_gb,omitempty"`

	// VolumeType Represents blockstorage volume type for each node.
	// It can be omitted only in cases when flavor_id is set and volume is local.
	VolumeType string `json:"volume_type,omitempty"`
}

// Cluster Provides information about cluster.
type Cluster struct {
	// Basic Specifies that cluster has only a single master and that control-plane is not in highly available mode.
	Basic bool `json:"basic"`

	// CniType CNI type represents type of CNI which is used in cluster.
	CniType ClusterCniType `json:"cni_type"`

	// CreatedAt Timestamp in UTC timezone of when the cluster has been created.
	CreatedAt time.Time `json:"created_at"`

	// EnableAutorepair Reflects if worker nodes are allowed to be reinstalled automatically in case of their unavailability or unhealthiness.
	EnableAutorepair bool `json:"enable_autorepair"`

	// EnablePatchVersionAutoUpgrade Specifies if Kubernetes version of the cluster is allowed to be upgraded automatically.
	EnablePatchVersionAutoUpgrade bool `json:"enable_patch_version_auto_upgrade"`

	// Id Uniq identifier of the cluster.
	Id string `json:"id"`

	// KubeApiIp Represents the IP of the Kubernetes API.
	KubeApiIp string `json:"kube_api_ip"`

	// KubeVersion Represents the current Kubernetes version of the cluster.
	KubeVersion string `json:"kube_version"`

	// KubernetesOptions Represents additional k8s options such as pod security policy,
	// feature gates and etc.
	KubernetesOptions KubernetesOptions `json:"kubernetes_options"`

	// Name Represents the name of the cluster.
	Name string `json:"name"`

	// NetworkId Contains reference to the network of the cluster.
	NetworkId string `json:"network_id"`

	// NetworkType Represents type of network l3vpn or default.
	NetworkType ClusterNetworkType `json:"network_type"`

	// Pool Represents the pool of where the cluster master nodes are located.
	Pool string `json:"pool"`

	// PrivateKubeApi Represents if kube API is available from the Internet or not.
	PrivateKubeApi bool `json:"private_kube_api"`

	// ProjectId Contains reference to the project of the cluster.
	ProjectId string `json:"project_id"`

	// Status Represents current status of the cluster.
	Status ClusterStatus `json:"status"`

	// SubnetId Contains reference to the subnet of the cluster.
	SubnetId string `json:"subnet_id"`

	// UpdatedAt Timestamp in UTC timezone of when the cluster has been updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ClusterCniType CNI type represents type of CNI which is used in cluster.
type ClusterCniType string

// ClusterNetworkType Represents type of network l3vpn or default.
type ClusterNetworkType string

// ClusterStatus Represents current status of the cluster.
type ClusterStatus string

// ClusterActions defines model for ClusterActions.
type ClusterActions struct {
	AddNodegroup                Action `json:"add_nodegroup"`
	Delete                      Action `json:"delete"`
	GetKubeconfig               Action `json:"get_kubeconfig"`
	RotateCertificates          Action `json:"rotate_certificates"`
	UpdateAuditLogs             Action `json:"update_audit_logs"`
	UpdateAutoRepair            Action `json:"update_auto_repair"`
	UpdateMaintenanceStart      Action `json:"update_maintenance_start"`
	UpdateOidc                  Action `json:"update_oidc"`
	UpdatePatchAutoUpgrade      Action `json:"update_patch_auto_upgrade"`
	UpdateRegistriesIntegration Action `json:"update_registries_integration"`
	UpgradeMinorVersion         Action `json:"upgrade_minor_version"`
	UpgradePatchVersion         Action `json:"upgrade_patch_version"`
}

// ClusterActionsResp Available actions of the cluster.
type ClusterActionsResp struct {
	Actions *ClusterActions `json:"actions,omitempty"`
}

// ClusterCreateBody ClusterCreateBody
// represents body content.
type ClusterCreateBody struct {
	Cluster *ClusterCreateStruct `json:"cluster,omitempty"`
}

// ClusterCreateStruct defines model for ClusterCreateStruct.
type ClusterCreateStruct struct {
	// AdditionalSoftware AdditionalSoftware represents information about additional software installed in the cluster.
	// Deprecated: do not use.
	AdditionalSoftware map[string]interface{} `json:"additional_software"`

	// Basic Basic specifies that only a single zonal master will be created.
	// It is needed if highly available control-plane is not required.
	// False by default.
	Basic           bool   `json:"basic"`
	CloudSubnetCidr string `json:"cloud_subnet_cidr,omitempty"`

	// CniCiliumSettings Represents settings for Cilium CNI if this CNI was chosen as "cni_type".
	// Otherwise settings will be ignored.
	CniCiliumSettings *CNICiliumSettings `json:"cni_cilium_settings,omitempty"`

	// CniType CNI type represents type of CNI which will be used in cluster.
	// Supported CNI types are CALICO and CILIUM. CALICO by default.
	CniType *string `json:"cni_type,omitempty"`

	// EnableAutorepair EnableAutorepair reflects if worker nodes are allowed to be reinstalled  automatically in case of their unavailability or unhealthiness.
	EnableAutorepair *bool `json:"enable_autorepair,omitempty"`

	// EnablePatchVersionAutoUpgrade EnablePatchVersionAutoUpgrade specifies if Kubernetes version of the cluster is allowed to be upgraded
	// automatically.
	// Enabled by default for regional clusters and disabled for zonal clusters.
	EnablePatchVersionAutoUpgrade *bool `json:"enable_patch_version_auto_upgrade,omitempty"`

	// KubeVersion KubeVersion represents the needed Kubernetes version of the cluster.
	// It should be in x.y.z format.
	KubeVersion string `json:"kube_version"`

	// KubernetesOptions Represents additional k8s options such as pod security policy,
	// feature gates and etc.
	KubernetesOptions *KubernetesOptions `json:"kubernetes_options,omitempty"`

	// MaintenanceWindowStart MaintenanceWindowStart represents UTC time of when the cluster will start its maintenance tasks.
	// It should be in hh:mm:ss format if provided.
	MaintenanceWindowStart string `json:"maintenance_window_start"`

	// Name Name represent the needed name of the cluster.
	// It shouldn't contain more than 32 symbols and can contain latin letters
	// with numbers and hyphens and start with a letter or a number.
	Name string `json:"name"`

	// NetworkId NetworkID contains a reference to the network of the cluster.
	// It can be set in cases where network is pre-created.
	NetworkId string `json:"network_id"`

	// NetworkType NetworkType represents which network will be used for master-node connection.
	NetworkType string `json:"network_type"`

	// Pool Pool represents the pool of where the cluster master nodes are located.
	Pool string `json:"pool"`

	// PrivateKubeApi PrivateKubeAPI specifies if kube API should be available from the Internet or not.
	// False by default.
	PrivateKubeApi bool `json:"private_kube_api"`

	// SubnetId SubnetID contains a reference to the subnet of the cluster.
	// It can be set in cases where subnet is pre-created.
	SubnetId string `json:"subnet_id"`
}

// ClusterDetailed Provides detailed information about cluster.
type ClusterDetailed struct {
	// AdditionalSoftware AdditionalSoftware represents information about additional software installed in the cluster.
	AdditionalSoftware map[string]interface{} `json:"additional_software"`

	// Basic Specifies that cluster has only a single master and that control-plane is not in highly available mode.
	Basic bool `json:"basic"`

	// CniCiliumSettings Represents settings for Cilium CNI if this CNI was chosen as "cni_type".
	// Otherwise settings will be ignored.
	CniCiliumSettings *CNICiliumSettings `json:"cni_cilium_settings,omitempty"`

	// CniType CNI type represents type of CNI which is used in cluster.
	CniType ClusterDetailedCniType `json:"cni_type"`

	// CreatedAt Timestamp in UTC timezone of when the cluster has been created.
	CreatedAt time.Time `json:"created_at"`

	// EnableAutorepair Reflects if worker nodes are allowed to be reinstalled automatically in case of their unavailability or unhealthiness.
	EnableAutorepair bool `json:"enable_autorepair"`

	// EnablePatchVersionAutoUpgrade Specifies if Kubernetes version of the cluster is allowed to be upgraded automatically.
	EnablePatchVersionAutoUpgrade bool `json:"enable_patch_version_auto_upgrade"`

	// Id Uniq identifier of the cluster.
	Id string `json:"id"`

	// KubeApiIp Represents the IP of the Kubernetes API.
	KubeApiIp string `json:"kube_api_ip"`

	// KubeVersion Represents the current Kubernetes version of the cluster.
	KubeVersion string `json:"kube_version"`

	// KubernetesOptions Represents additional k8s options such as pod security policy,
	// feature gates and etc.
	KubernetesOptions KubernetesOptions `json:"kubernetes_options"`

	// MaintenanceLastStart MaintenanceLastStart is the timestamp in UTC timezone of the last cluster maintenance start.
	MaintenanceLastStart time.Time `json:"maintenance_last_start"`

	// MaintenanceWindowEnd MaintenanceWindowEnd represents UTC time in "hh:mm:ss" format of when the cluster will end its
	// maintenance tasks.
	MaintenanceWindowEnd string `json:"maintenance_window_end"`

	// MaintenanceWindowStart MaintenanceWindowStart represents UTC time in "hh:mm:ss" format of when the cluster will start its
	// maintenance tasks.
	MaintenanceWindowStart string `json:"maintenance_window_start"`

	// Name Represents the name of the cluster.
	Name string `json:"name"`

	// NetworkId Contains reference to the network of the cluster.
	NetworkId string `json:"network_id"`

	// NetworkType Represents type of network l3vpn or default.
	NetworkType ClusterDetailedNetworkType `json:"network_type"`

	// PkiTreeUpdatedAt PKITreeUpdatedAt represents the timestamp in UTC timezone of when the PKI-tree of the cluster
	// has been updated.
	PkiTreeUpdatedAt time.Time `json:"pki_tree_updated_at"`

	// Pool Represents the pool of where the cluster master nodes are located.
	Pool string `json:"pool"`

	// PrivateKubeApi Represents if kube API is available from the Internet or not.
	PrivateKubeApi bool `json:"private_kube_api"`

	// ProjectId Contains reference to the project of the cluster.
	ProjectId string `json:"project_id"`

	// Status Represents current status of the cluster.
	Status ClusterDetailedStatus `json:"status"`

	// SubnetId Contains reference to the subnet of the cluster.
	SubnetId string `json:"subnet_id"`

	// UpdatedAt Timestamp in UTC timezone of when the cluster has been updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ClusterDetailedCniType CNI type represents type of CNI which is used in cluster.
type ClusterDetailedCniType string

// ClusterDetailedNetworkType Represents type of network l3vpn or default.
type ClusterDetailedNetworkType string

// ClusterDetailedStatus Represents current status of the cluster.
type ClusterDetailedStatus string

// ClusterList List of clusters.
type ClusterList struct {
	Clusters *[]Cluster `json:"clusters,omitempty"`
}

// ClusterResp Cluster response.
type ClusterResp struct {
	// Cluster Provides detailed information about cluster.
	Cluster *ClusterDetailed `json:"cluster,omitempty"`
}

// ClusterUpdateBody ClusterUpdateBody
// represents body content.
type ClusterUpdateBody struct {
	Cluster *ClusterUpdateStruct `json:"cluster,omitempty"`
}

// ClusterUpdateStruct defines model for ClusterUpdateStruct.
type ClusterUpdateStruct struct {
	// CniCiliumSettings Represents settings for Cilium CNI if this CNI was chosen as "cni_type".
	// Otherwise settings will be ignored.
	CniCiliumSettings *CNICiliumSettings `json:"cni_cilium_settings,omitempty"`

	// EnableAutorepair EnableAutorepair reflects if worker nodes are allowed to be reinstalled  automatically in case of their unavailability or unhealthiness.
	EnableAutorepair *bool `json:"enable_autorepair,omitempty"`

	// EnablePatchVersionAutoUpgrade EnablePatchVersionAutoUpgrade specifies if Kubernetes version of the cluster is allowed to be upgraded
	// automatically.
	// Enabled by default for regional clusters and disabled for zonal clusters.
	EnablePatchVersionAutoUpgrade *bool `json:"enable_patch_version_auto_upgrade,omitempty"`

	// KubernetesOptions Represents additional k8s options such as pod security policy,
	// feature gates and etc.
	KubernetesOptions *KubernetesOptions `json:"kubernetes_options,omitempty"`

	// MaintenanceWindowStart MaintenanceWindowStart represents UTC time of when the cluster will start its maintenance tasks.
	// It should be in hh:mm:ss format if provided.
	MaintenanceWindowStart *string `json:"maintenance_window_start,omitempty"`
}

// ClustersLimits defines model for ClustersLimits.
type ClustersLimits struct {
	// BasicClustersLimit Represents the minimum number of basic clusters in project.
	BasicClustersLimit int `json:"basic_clusters_limit"`

	// HighAvailabilityClustersLimit Represents the maximum number of high-availability clusters in project.
	HighAvailabilityClustersLimit int `json:"high_availability_clusters_limit"`
}

// DedicatedNodegroupConfig Represents configuration for dedicated based nodegroups.
type DedicatedNodegroupConfig struct {
	// CreateStoragePartition Determines is storage partition should be created on fastest disk.
	CreateStoragePartition *bool `json:"create_storage_partition,omitempty"`

	// Currency Represents which balance will be used to order new servers.
	// ## Note 💡
	// ```
	// main - to use main balance. This option will be used as default.
	// bonus - to use bonus balance.
	// ```
	Currency      *DedicatedNodegroupConfigCurrency `json:"currency,omitempty"`
	PricePlanUuid string                            `json:"price_plan_uuid"`

	// RootSizeGb RootSizeGB represents size of "/" partition on dedicated nodes.
	RootSizeGb  *int64 `json:"root_size_gb,omitempty"`
	ServiceUuid string `json:"service_uuid"`
}

// DedicatedNodegroupConfigCurrency Represents which balance will be used to order new servers.
// ## Note 💡
// ```
// main - to use main balance. This option will be used as default.
// bonus - to use bonus balance.
// ```
type DedicatedNodegroupConfigCurrency string

// ExtendedWorkerNodeLimits defines model for ExtendedWorkerNodeLimits.
type ExtendedWorkerNodeLimits struct {
	// CpuDriveCoefficient Represents calculation coefficient for local drives relative to the number of CPUs.
	// The final limit will be calculated using the formula: cpu_number * cpu_drive_coefficient
	CpuDriveCoefficient *int `json:"cpu_drive_coefficient,omitempty"`

	// CpuRamCoefficient Represents calculation coefficient for RAM size relative to the number of CPUs.
	// The final limit will be calculated using the formula: cpu_number * cpu_ram_coefficient
	CpuRamCoefficient *int `json:"cpu_ram_coefficient,omitempty"`

	// MaxLocalDriveGbPerNode Represents maximum local volume size in Gigabytes for each worker-node.
	// For network-attached volumes will be used default limits.
	MaxLocalDriveGbPerNode *int `json:"max_local_drive_gb_per_node,omitempty"`

	// MaxRamMbPerNode Represents maximum RAM size in Megabytes for each worker-node.
	MaxRamMbPerNode *int `json:"max_ram_mb_per_node,omitempty"`

	// MinLocalDriveGbPerNode Represents minimum local volume size in Gigabytes for each worker-node.
	// For network-attached volumes will be used default limits.
	MinLocalDriveGbPerNode *int `json:"min_local_drive_gb_per_node,omitempty"`

	// MinRamMbPerNode Represents minimum RAM size in Megabytes for each worker-node.
	MinRamMbPerNode *int `json:"min_ram_mb_per_node,omitempty"`
}

// FeatureGatesList List of available feature gates.
type FeatureGatesList struct {
	FeatureGates *[]AvailableFeatureGates `json:"feature_gates,omitempty"`
}

// KubeVersionInfo Kubernetes version information.
type KubeVersionInfo struct {
	// Version Supported Kubernetes version in format: "X.Y.Z"
	Version *string `json:"version,omitempty"`

	// IsDefault Flag indicates if kubernetes version is default.
	IsDefault *bool `json:"is_default,omitempty"`
}

// KubeVersionsList List of supported Kubernetes versions.
type KubeVersionsList struct {
	KubeVersions *[]KubeVersionInfo `json:"kube_versions,omitempty"`
}

// KubernetesOptions Represents additional k8s options such as pod security policy,
// feature gates and etc.
type KubernetesOptions struct {
	// AdmissionControllers Represents turned on admission controllers for the cluster.
	AdmissionControllers []string  `json:"admission_controllers"`
	AuditLogs            AuditLogs `json:"audit_logs"`

	// FeatureGates Represents turned on feature gates
	FeatureGates []string `json:"feature_gates"`

	// Oidc OIDC represents parameters to connect client's OIDC provider with kubernetes.
	Oidc OIDC `json:"oidc"`

	// X509CaCertificates Represent custom X509 CA certs which can be used for cluster components. Certificates should be encoded to base64 format. Note 💡 ``` X509CaCertificates can be disabled for some pools. ```
	X509CaCertificates string `json:"x509_ca_certificates,omitempty"`
}

// LimitsList Default limits list
type LimitsList struct {
	Cluster ClustersLimits `json:"cluster"`

	// ExtendedLimits Represents flexible limits rules.
	ExtendedLimits *map[string]ExtendedWorkerNodeLimits `json:"extended_limits,omitempty"`
	Nodegroup      NodegroupLimits                      `json:"nodegroup"`
	WorkerNode     WorkerNodeLimits                     `json:"worker_node"`
}

// Node Provides information about node.
type Node struct {
	// CreatedAt Timestamp in UTC timezone of when the node has been created.
	CreatedAt time.Time `json:"created_at"`

	// Hostname Represents a hostname of the node.
	Hostname string `json:"hostname"`

	// Id Uniq identifier of the node.
	Id string `json:"id"`

	// Ip Represents IP address of the node.
	Ip string `json:"ip"`

	// NodegroupId Contains nodegroup identifier.
	NodegroupId string `json:"nodegroup_id"`

	// ProviderServerId Contains server identifier in external provider (OpenStack, dedicated resource).
	ProviderServerId string `json:"provider_server_id"`

	// UpdatedAt Timestamp in UTC timezone of when the node has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodeResp Node response.
type NodeResp struct {
	// Node Provides information about node.
	Node Node `json:"node"`
}

// NodegorupAdditionalInfo Provides additional information about nodegroup like userdata, etc.
type NodegorupAdditionalInfo struct {
	// UserData True when nodegroup has user_data field filled.
	UserData bool `json:"user_data"`
}

// Nodegroup Provides information about nodegroup.
type Nodegroup struct {
	// AutoscaleMaxNodes Represents maximum possible number of worker nodes in the nodegroup.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Represents minimum possible number of worker nodes in the nodegroup.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// Cidr Represents a CIDR for nodegroup specified by client.
	Cidr *string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Represents configuration for cloud based nodegroups.
	CloudNodegroupConfig *CloudNodegroupConfig `json:"cloud_nodegroup_config,omitempty"`

	// ClusterId Uniq identifier of the cluster.
	ClusterId string `json:"cluster_id"`

	// CreatedAt Timestamp in UTC timezone of when the nodegroup has been created.
	CreatedAt time.Time `json:"created_at"`

	// DedicatedNodegroupConfig Represents configuration for dedicated based nodegroups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Reflects if the nodegroup is allowed to be scaled automatically.
	EnableAutoscale bool `json:"enable_autoscale"`

	// Id Uniq identifier of the nodegroup.
	Id string `json:"id"`

	// InstallNvidiaDevicePlugin Indicates if nvidia device plugin installation was requested. Applicable only for nodegroups with GPU nodes.
	InstallNvidiaDevicePlugin bool `json:"install_nvidia_device_plugin"`

	// Labels Represents an object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels map[string]string `json:"labels"`

	// NodegroupType Represents type of nodes in nodegroup. ## Note 💡 ` STANDARD      -- for all nodes from configs: standard line, cpu line, memory line; GPU           -- for nodes from gpu line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from gpu line; `
	NodegroupType NodegroupNodegroupType `json:"nodegroup_type"`

	// Nodes Contains list of all nodes in the nodegroup.
	Nodes []Node `json:"nodes"`

	// Preemptible Represents if nodes in the nodegroup are preemptible.
	Preemptible bool `json:"preemptible"`

	// Segment Represents segment for all nodes in the nodegroup.
	Segment string `json:"segment"`

	// Status Represents current status of the nodegroup.
	Status NodegroupStatus `json:"status"`

	// Taints Represents a list of nodegroup taints.
	Taints []NodegroupTaint `json:"taints"`

	// UpdatedAt Timestamp in UTC timezone of when the nodegroup has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodegroupNodegroupType Represents type of nodes in nodegroup. ## Note 💡 ` STANDARD      -- for all nodes from configs: standard line, cpu line, memory line; GPU           -- for nodes from gpu line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from gpu line; `
type NodegroupNodegroupType string

// NodegroupStatus Represents current status of the nodegroup.
type NodegroupStatus string

// NodegroupActions defines model for NodegroupActions.
type NodegroupActions struct {
	Delete                  Action `json:"delete"`
	DeleteNode              Action `json:"delete_node"`
	ReinstallNode           Action `json:"reinstall_node"`
	Resize                  Action `json:"resize"`
	UpdateAutoscalingMinMax Action `json:"update_autoscaling_min_max"`
	UpdateLabels            Action `json:"update_labels"`
	UpdateTaints            Action `json:"update_taints"`
}

// NodegroupActionsResp Available actions of the nodegroup.
type NodegroupActionsResp struct {
	Actions *NodegroupActions `json:"actions,omitempty"`
}

// NodegroupCreateStruct defines model for NodegroupCreateStruct.
type NodegroupCreateStruct struct {
	// AutoscaleMaxNodes Represents maximum possible number of worker nodes in the nodegroup.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Represents minimum possible number of worker nodes in the nodegroup.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// Cidr Represents a CIDR for nodegroup specified by client.
	Cidr string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Represents configuration for cloud based nodegroups.
	CloudNodegroupConfig *CloudNodegroupConfig `json:"cloud_nodegroup_config,omitempty"`

	// Count Count represents nodes count for this nodegroup.
	Count int64 `json:"count"`

	// DedicatedNodegroupConfig Represents configuration for dedicated based nodegroups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Reflects if the nodegroup is allowed to be scaled automatically.
	EnableAutoscale *bool `json:"enable_autoscale,omitempty"`

	// InstallNvidiaDevicePlugin Indicates if nvidia device plugin installation was requested. Applicable only for nodegroups with GPU nodes.
	InstallNvidiaDevicePlugin *bool `json:"install_nvidia_device_plugin,omitempty"`

	// Labels Represents an object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels *map[string]string `json:"labels,omitempty"`

	// Pool Should contain the valid pool name where nodegroup nodes will be created.
	Pool string `json:"pool"`

	// Preemptible Represents if nodes in the nodegroup are preemptible.
	Preemptible bool `json:"preemptible,omitempty"`

	// Taints Represents a list of nodegroup taints.
	Taints *[]NodegroupTaint `json:"taints,omitempty"`

	// UserData Represents base64 data which is used to pass a script that worker nodes run on boot.
	UserData string `json:"user_data,omitempty"`
}

// NodegroupDetailed defines model for NodegroupDetailed.
type NodegroupDetailed struct {
	// AutoscaleMaxNodes Represents maximum possible number of worker nodes in the nodegroup.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Represents minimum possible number of worker nodes in the nodegroup.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// Cidr Represents a CIDR for nodegroup specified by client.
	Cidr *string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Represents configuration for cloud based nodegroups.
	CloudNodegroupConfig *CloudNodegroupConfig `json:"cloud_nodegroup_config,omitempty"`

	// ClusterId Uniq identifier of the cluster.
	ClusterId string `json:"cluster_id"`

	// CreatedAt Timestamp in UTC timezone of when the nodegroup has been created.
	CreatedAt time.Time `json:"created_at"`

	// DedicatedNodegroupConfig Represents configuration for dedicated based nodegroups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Reflects if the nodegroup is allowed to be scaled automatically.
	EnableAutoscale bool `json:"enable_autoscale"`

	// Id Uniq identifier of the nodegroup.
	Id string `json:"id"`

	// InstallNvidiaDevicePlugin Indicates if nvidia device plugin installation was requested. Applicable only for nodegroups with GPU nodes.
	InstallNvidiaDevicePlugin bool `json:"install_nvidia_device_plugin"`

	// Labels Represents an object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels map[string]string `json:"labels"`

	// NodegroupType Represents type of nodes in nodegroup. ## Note 💡 ` STANDARD      -- for all nodes from configs: standard line, cpu line, memory line; GPU           -- for nodes from gpu line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from gpu line; `
	NodegroupType NodegroupDetailedNodegroupType `json:"nodegroup_type"`

	// Nodes Contains list of all nodes in the nodegroup.
	Nodes []Node `json:"nodes"`

	// Preemptible Represents if nodes in the nodegroup are preemptible.
	Preemptible bool `json:"preemptible"`

	// Segment Represents segment for all nodes in the nodegroup.
	Segment string `json:"segment"`

	// Status Represents current status of the nodegroup.
	Status NodegroupDetailedStatus `json:"status"`

	// Taints Represents a list of nodegroup taints.
	Taints []NodegroupTaint `json:"taints"`

	// UpdatedAt Timestamp in UTC timezone of when the nodegroup has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// UserData Represents base64 data which is used to pass a script that worker nodes run on boot.
	UserData string `json:"user_data,omitempty"`
}

// NodegroupDetailedNodegroupType Represents type of nodes in nodegroup. ## Note 💡 ` STANDARD      -- for all nodes from configs: standard line, cpu line, memory line; GPU           -- for nodes from gpu line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from gpu line; `
type NodegroupDetailedNodegroupType string

// NodegroupDetailedStatus Represents current status of the nodegroup.
type NodegroupDetailedStatus string

// NodegroupLimits defines model for NodegroupLimits.
type NodegroupLimits struct {
	// MaxNodegroupsPerPool Represents maximum number of nodegroups in the pool.
	MaxNodegroupsPerPool int `json:"max_nodegroups_per_pool"`

	// MaxNodesPerNodegroup Represents the maximum number of nodes in nodegroup.
	MaxNodesPerNodegroup int `json:"max_nodes_per_nodegroup"`

	// MinNodesPerDedicatedNodegroup Represents the minimum number of nodes in dedicated nodegroup.
	MinNodesPerDedicatedNodegroup int `json:"min_nodes_per_dedicated_nodegroup"`

	// MinNodesPerNodegroup Represents the minimum number of nodes in nodegroup.
	MinNodesPerNodegroup int `json:"min_nodes_per_nodegroup"`
}

// NodegroupList List of nodegroups of the cluster.
type NodegroupList struct {
	Nodegroups []NodegroupListItem `json:"nodegroups"`
}

// NodegroupListItem defines model for NodegroupListItem.
type NodegroupListItem struct {
	// AutoscaleMaxNodes Represents maximum possible number of worker nodes in the nodegroup.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Represents minimum possible number of worker nodes in the nodegroup.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// AvailableAdditionalInfo Provides additional information about nodegroup like userdata, etc.
	AvailableAdditionalInfo NodegorupAdditionalInfo `json:"available_additional_info"`

	// Cidr Represents a CIDR for nodegroup specified by client.
	Cidr *string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Represents configuration for cloud based nodegroups.
	CloudNodegroupConfig *CloudNodegroupConfig `json:"cloud_nodegroup_config,omitempty"`

	// ClusterId Uniq identifier of the cluster.
	ClusterId string `json:"cluster_id"`

	// CreatedAt Timestamp in UTC timezone of when the nodegroup has been created.
	CreatedAt time.Time `json:"created_at"`

	// DedicatedNodegroupConfig Represents configuration for dedicated based nodegroups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Reflects if the nodegroup is allowed to be scaled automatically.
	EnableAutoscale bool `json:"enable_autoscale"`

	// Id Uniq identifier of the nodegroup.
	Id string `json:"id"`

	// InstallNvidiaDevicePlugin Indicates if nvidia device plugin installation was requested. Applicable only for nodegroups with GPU nodes.
	InstallNvidiaDevicePlugin bool `json:"install_nvidia_device_plugin"`

	// Labels Represents an object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels map[string]string `json:"labels"`

	// NodegroupType Represents type of nodes in nodegroup. ## Note 💡 ` STANDARD      -- for all nodes from configs: standard line, cpu line, memory line; GPU           -- for nodes from gpu line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from gpu line; `
	NodegroupType NodegroupListItemNodegroupType `json:"nodegroup_type"`

	// Nodes Contains list of all nodes in the nodegroup.
	Nodes []Node `json:"nodes"`

	// Preemptible Represents if nodes in the nodegroup are preemptible.
	Preemptible bool `json:"preemptible"`

	// Segment Represents segment for all nodes in the nodegroup.
	Segment string `json:"segment"`

	// Status Represents current status of the nodegroup.
	Status NodegroupListItemStatus `json:"status"`

	// Taints Represents a list of nodegroup taints.
	Taints []NodegroupTaint `json:"taints"`

	// UpdatedAt Timestamp in UTC timezone of when the nodegroup has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodegroupListItemNodegroupType Represents type of nodes in nodegroup. ## Note 💡 ` STANDARD      -- for all nodes from configs: standard line, cpu line, memory line; GPU           -- for nodes from gpu line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from gpu line; `
type NodegroupListItemNodegroupType string

// NodegroupListItemStatus Represents current status of the nodegroup.
type NodegroupListItemStatus string

// NodegroupResizeBody Represents body content.
type NodegroupResizeBody struct {
	Nodegroup NodegroupResizeStruct `json:"nodegroup"`
}

// NodegroupResizeStruct defines model for NodegroupResizeStruct.
type NodegroupResizeStruct struct {
	// Desired Desired represents desired amount of nodes for this nodegroup.
	Desired int64 `json:"desired"`
}

// NodegroupResp Nodegroup response.
type NodegroupResp struct {
	// Nodegroup Provides detailed information about nodegroup.
	Nodegroup NodegroupDetailed `json:"nodegroup"`
}

// NodegroupTaint Represents k8s nodegroup taint that applies for every node in the group.
type NodegroupTaint struct {
	// Effect Effect for taint.
	Effect NodegroupTaintEffect `json:"effect"`

	// Key Key for taint.
	Key string `json:"key"`

	// Value Value for taint.
	Value string `json:"value"`
}

// NodegroupTaintEffect Effect for taint.
type NodegroupTaintEffect string

// NodegroupUpdateBody Represents body content.
type NodegroupUpdateBody struct {
	Nodegroup NodegroupUpdateStruct `json:"nodegroup"`
}

// NodegroupUpdateStruct defines model for NodegroupUpdateStruct.
type NodegroupUpdateStruct struct {
	// AutoscaleMaxNodes Represents maximum possible number of worker nodes in the cloud nodegroup.
	AutoscaleMaxNodes *int `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Represents minimum possible number of worker nodes in the cloud nodegroup.
	AutoscaleMinNodes *int `json:"autoscale_min_nodes,omitempty"`

	// EnableAutoscale Reflects if the cloud nodegroup is allowed to be scaled automatically.
	EnableAutoscale *bool `json:"enable_autoscale,omitempty"`

	// Labels Represents an object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels *map[string]string `json:"labels,omitempty"`

	// Taints Represents a list of nodegroup taints.
	Taints *[]NodegroupTaint `json:"taints,omitempty"`
}

// NodegroupsCreateBody Represents body content for creating multiple nodegroups.
type NodegroupsCreateBody struct {
	Nodegroups []NodegroupCreateStruct `json:"nodegroups"`
}

// OIDC OIDC represents parameters to connect client's OIDC provider with kubernetes.
type OIDC struct {
	// CaCerts CACerts represent optional custom CA certs chain in X509 PEM format of provider's SSL certificate.
	// Will be written to file on masters which will be passed in `--oidc-ca-file` kube-apiserver flag.
	CaCerts string `json:"ca_certs,omitempty"`

	// CaCertsExpiration CACertsExpiration represents date and time when the first of provided CA certificates will be expired.
	CaCertsExpiration *time.Time `json:"ca_certs_expiration,omitempty"`

	// ClientId Represents required client id that all tokens must be issued for. Will be placed in `--oidc-client-id` flag. It is required when enabled = true.
	ClientId string `json:"client_id"`

	// Enabled If `enabled` OIDC should be turned on in the cluster.
	// False by default.
	Enabled bool `json:"enabled"`

	// GroupsClaim Represents optional JWT claim to use as the user's group. By default, `groups`. Will be placed in `--oidc-groups-claim` flag.
	GroupsClaim string `json:"groups_claim"`

	// IssuerUrl Represents URL of the provider that allows the API server to discover public signing keys. Will be placed in `--oidc-issuer-url` flag. It is required when enabled = true.
	IssuerUrl string `json:"issuer_url"`

	// ProviderName Represents custom user defined name of the provider. It is not used in the cluster directly. It is required when enabled = true.
	ProviderName string `json:"provider_name"`

	// UsernameClaim Represents optional JWT claim to use as the username. By default, `sub`. Will be placed in `--oidc-username-claim` flag.
	UsernameClaim string `json:"username_claim"`
}

// OptionNamesAC List of available admission controllers.
type OptionNamesAC = []string

// OptionNamesFG List of available feature gate names.
type OptionNamesFG = []string

// RegistriesIntegration Registries integration of the cluster.
type RegistriesIntegration struct {
	Registries []RegistryWithMeta `json:"registries"`

	// Status Status represents status of the registries' integration.
	Status RegistriesIntegrationStatus `json:"status"`
}

// RegistriesIntegrationStatus Status represents status of the registries' integration.
type RegistriesIntegrationStatus string

// RegistriesIntergrationCreateBody Represents body content.
type RegistriesIntergrationCreateBody struct {
	Registries []RegistriesIntergrationCreateStruct `json:"registries"`
}

// RegistriesIntergrationCreateStruct defines model for RegistriesIntergrationCreateStruct.
type RegistriesIntergrationCreateStruct struct {
	// Id Represents unique identifier of the registry.
	Id string `json:"id"`
}

// RegistriesIntergrationUpdateBody Represents body content.
type RegistriesIntergrationUpdateBody struct {
	Registries []RegistriesIntergrationUpdateStruct `json:"registries"`
}

// RegistriesIntergrationUpdateStruct defines model for RegistriesIntergrationUpdateStruct.
type RegistriesIntergrationUpdateStruct struct {
	// Id Represents unique identifier of the registry.
	Id string `json:"id"`
}

// RegistryWithMeta Registry integration with metadata.
type RegistryWithMeta struct {
	// Id Represents unique identifier of the registry.
	Id string `json:"id"`

	// Name Represents name of the registry.
	Name string `json:"name"`
}

// ResourceUsage Project resource usage.
type ResourceUsage struct {
	// ClustersCount Amount of clusters in the project
	ClustersCount *int64 `json:"clusters_count,omitempty"`

	// NodegroupsCount Amount of nodegroups in the project
	NodegroupsCount *int64 `json:"nodegroups_count,omitempty"`
}

// Task Provides information about task.
type Task struct {
	// ClusterId Contains cluster identifier.
	ClusterId string `json:"cluster_id"`

	// ErrorDetails Provides information about error details of the task. Disabled by default, to enable use query parameter 'withErrorDetails=true'.
	ErrorDetails *TaskErrorDetails `json:"error_details,omitempty"`

	// Id The identifier of the task.
	Id string `json:"id"`

	// NodegroupId Contains nodegroup identifier.
	NodegroupId *string `json:"nodegroup_id,omitempty"`

	// StartedAt The timestamp in UTC timezone of when the task has been started.
	StartedAt time.Time `json:"started_at"`

	// Status Represents current status of the task.
	Status TaskStatus `json:"status"`

	// Type Represents task's type.
	Type string `json:"type"`

	// UpdatedAt The timestamp in UTC timezone of when the task has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TaskStatus Represents current status of the task.
type TaskStatus string

// TaskErrorDetails Provides information about error details of the task. Disabled by default, to enable use query parameter 'withErrorDetails=true'.
type TaskErrorDetails struct {
	// Code Represents task's error code.
	Code int64 `json:"code"`

	// Details Contains task's error helpful information.
	Details *string `json:"details,omitempty"`

	// Name Represents task's error short description.
	Name string `json:"name"`
}

// TaskList Provides information about tasks of the cluster.
type TaskList struct {
	// Count Count of all tasks of the cluster.
	Count int64  `json:"count"`
	Tasks []Task `json:"tasks"`
}

// TaskResp Provides information about task of the cluster.
type TaskResp struct {
	// Task Provides information about task.
	Task Task `json:"task"`
}

// WorkerNodeLimits defines model for WorkerNodeLimits.
type WorkerNodeLimits struct {
	// MaxCpusPerNode Represents the maximum number of CPUs for each worker-node.
	MaxCpusPerNode int `json:"max_cpus_per_node"`

	// MaxRamMbPerNode Represents maximum RAM size in Megabytes for each worker-node.
	MaxRamMbPerNode int `json:"max_ram_mb_per_node"`

	// MaxVolumeGbPerNode Represents maximum volume size in Gigabytes for each worker-node.
	MaxVolumeGbPerNode int `json:"max_volume_gb_per_node"`

	// MinCpusPerNode Represents the minimum number of CPUs for each worker-node.
	MinCpusPerNode int `json:"min_cpus_per_node"`

	// MinRamMbPerNode Represents minimum RAM size in Megabytes for each worker-node.
	MinRamMbPerNode int `json:"min_ram_mb_per_node"`

	// MinVolumeGbPerNode Represents minimum volume size in Gigabytes for each worker-node.
	MinVolumeGbPerNode int `json:"min_volume_gb_per_node"`
}

// GenericError Generic Error.
type GenericError struct {
	Error struct {
		// Message Error Message.
		Message string `json:"message"`
	} `json:"error"`
}

// GenericNoContent Generic no content response.
type GenericNoContent = interface{}

// GenericNotFoundError Generic message about not found error for any object.
type GenericNotFoundError struct {
	Error struct {
		// Id Object ID.
		Id string `json:"id"`

		// Message Message of the error.
		Message string `json:"message"`
	} `json:"error"`
}

// ClusterId defines model for cluster_id.
type ClusterId = string

// KubeVersion defines model for kube_version.
type KubeVersion = string

// Lang defines model for lang.
type Lang string

// Limit defines model for limit.
type Limit = uint64

// NodeId defines model for node_id.
type NodeId = string

// NodegroupId defines model for nodegroup_id.
type NodegroupId = string

// Offset defines model for offset.
type Offset = uint64

// RegistryId defines model for registry_id.
type RegistryId = string

// TaskId defines model for task_id.
type TaskId = string

// WithErrorDetails defines model for with_error_details.
type WithErrorDetails = bool

// GetClusterActionsV2Params defines parameters for GetClusterActionsV2.
type GetClusterActionsV2Params struct {
	// Lang Language on which response should be returned.
	Lang *GetClusterActionsV2ParamsLang `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetClusterActionsV2ParamsLang defines parameters for GetClusterActionsV2.
type GetClusterActionsV2ParamsLang string

// GetNodegroupActionsV2Params defines parameters for GetNodegroupActionsV2.
type GetNodegroupActionsV2Params struct {
	// Lang Language on which response should be returned.
	Lang *GetNodegroupActionsV2ParamsLang `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetNodegroupActionsV2ParamsLang defines parameters for GetNodegroupActionsV2.
type GetNodegroupActionsV2ParamsLang string

// ListTasksV2Params defines parameters for ListTasksV2.
type ListTasksV2Params struct {
	// Limit Limit of elements in response.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of elements to skip.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// WithErrorDetails Flag to show error details at task view.
	WithErrorDetails *WithErrorDetails `form:"with_error_details,omitempty" json:"with_error_details,omitempty"`
}

// GetTaskV2Params defines parameters for GetTaskV2.
type GetTaskV2Params struct {
	// WithErrorDetails Flag to show error details at task view.
	WithErrorDetails *WithErrorDetails `form:"with_error_details,omitempty" json:"with_error_details,omitempty"`
}

// GetLimitsV2Params defines parameters for GetLimitsV2.
type GetLimitsV2Params struct {
	// KubeVersion Version of Kubernetes for which response should be returned.
	KubeVersion *KubeVersion `form:"kube_version,omitempty" json:"kube_version,omitempty"`
}

// CreateClusterV2JSONRequestBody defines body for CreateClusterV2 for application/json ContentType.
type CreateClusterV2JSONRequestBody = ClusterCreateBody

// UpdateClusterV2JSONRequestBody defines body for UpdateClusterV2 for application/json ContentType.
type UpdateClusterV2JSONRequestBody = ClusterUpdateBody

// CreateNodegroupsV2JSONRequestBody defines body for CreateNodegroupsV2 for application/json ContentType.
type CreateNodegroupsV2JSONRequestBody = NodegroupsCreateBody

// UpdateNodegroupV2JSONRequestBody defines body for UpdateNodegroupV2 for application/json ContentType.
type UpdateNodegroupV2JSONRequestBody = NodegroupUpdateBody

// ResizeNodegroupV2JSONRequestBody defines body for ResizeNodegroupV2 for application/json ContentType.
type ResizeNodegroupV2JSONRequestBody = NodegroupResizeBody

// CreateRegistriesV2JSONRequestBody defines body for CreateRegistriesV2 for application/json ContentType.
type CreateRegistriesV2JSONRequestBody = RegistriesIntergrationCreateBody

// UpdateRegistriesV2JSONRequestBody defines body for UpdateRegistriesV2 for application/json ContentType.
type UpdateRegistriesV2JSONRequestBody = RegistriesIntergrationUpdateBody
